In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df=pd.read_csv("/content/healthcare_raw(unsupervised data).csv")

In [24]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         500 non-null    object
 1   Gender             500 non-null    object
 2   Age                500 non-null    int64
 3   Medical_Condition  500 non-null    object
 4   Admission_Date     500 non-null    object
 5   Admission_Type     500 non-null    object
 6   Medical_Code       485 non-null    object
 7   Billing_Amount     500 non-null    float64
 8   Discharge_Date     500 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB

In [26]:
df.describe()

              Age  Billing_Amount
count  500.000000       500.00000
mean    50.106000      7249.00100
std     15.328035      3198.96932
min     22.000000      2300.00000
25%     37.000000      4400.00000
50%     50.000000      6950.00000
75%     63.000000      9400.00000
max     78.000000     14200.00000

In [27]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [30]:
df['Medical_Code']=df['Medical_Code'].fillna("Unknown")

In [31]:
df.isnull().sum()

Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [36]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])

/tmp/ipykernel_770/2836827915.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])

In [37]:
df['hospital_stay_days']=(df['Discharge_Date']-df['Admission_Date'])
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date,hospital_stay_days
0,P1001,Male,45,Hypertension,2026-01-15,Urgent,ICD10 I10,4500.0,2026-01-20,5 days
1,P1002,Female,32,Pneumonia,2026-01-16,Emergency,ICD10 J18,6700.5,2026-01-22,6 days
2,P1003,Male,68,Diabetes Type 2,2026-01-16,Routine,ICD10 E11,3200.0,2026-01-18,2 days
3,P1004,Female,55,Asthma,2026-01-17,Emergency,ICD10 J45,5800.0,2026-01-19,2 days
4,P1005,Male,29,Fracture,2026-01-17,Urgent,ICD10 S52,8500.0,2026-01-25,8 days

In [40]:
df['Medical_Condition'].value_counts()

Medical_Condition
COPD                       34
Appendicitis               33
Stroke                     33
Pneumonia                  31
Heart Failure              30
Kidney Stone               28
Hypertension               28
Heart Attack               27
Fracture                   22
Gastritis                  21
Skin Infection             20
Back Pain                  20
Asthma                     19
Parkinson's Disease        19
Urinary Tract Infection    18
Pregnancy                  16
Diabetes Type 2            16
Allergic Reaction          15
Gallstones                 15
Diabetes Type 1            15
Osteoporosis               12
Osteoarthritis             12
Anxiety Disorder            9
Migraine                    6
Hypothyroidism              1
Name: count, dtype: int64